server:
  port: 9001

spring:
  application:
    name: dubbo-cusumer

#注册中心地址
#dubbo:
#  registry:
#    address: zookeeper://192.168.1.9:2181
#端口号可以写在address中，也可以单独写。实质是从address中获取的port是null，后面设置的port覆盖了null
#dubbo:
#  registry:
#    port: 2181


dubbo:
  protocol:
    name: dubbo #指定dubbo使用的协议
    port: 20880 #指定dubbo使用的端口
  registry:
    timeout: 10000 #指定注册到zk上超时时间，ms

